### ISSUE TITLE
image-converter: scale percentage not applied, uses custom width value (default: 1000 px)

### ISSUE THREAD

**Issue by genygilles** [mate-desktop/caja-extensions#104]
#### Steps to reproduce the behaviour

[Green-Wall-Logo](https://user-images.githubusercontent.com/51641167/114855736-9010ef80-9de6-11eb-82a3-d36018523e87.png)

![image](https://user-images.githubusercontent.com/51641167/114855271-0eb95d00-9de6-11eb-8e4b-0356c2b1f65e.png)

* Open image-converter
* Select **Scale** (default 50%)
* **Resize**

#### Expected behaviour

The image should be resized with a 50% scale.

#### Actual behaviour

[Green-Wall-Logo resized50scale](https://user-images.githubusercontent.com/51641167/114855813-a454ec80-9de6-11eb-931d-af60359a4c61.png)

The resized image has the width value set in Custom size input (default: 1000 px).

#### MATE general version

MATE 1.24.0

#### Package version

1.24.0-1

#### Linux Distribution

Release 20.04.2 LTS (Focal Fossa) 64-bit
Kernel Linux 5.4.0-71-generic x86_64

#### Link to bugreport of your Distribution (requirement)

https://bugs.launchpad.net/ubuntu-mate

**Comment by dahenry** [comment]
When selecting a custom scale, it behaves like having selected the custom size option. The code path enters line caja-image-resizer.c:327 instead of caja-image-resizer.c:324. Why is this branch not properly evaluated?

In caja-image-resize.ui, the GtkRadioButton from line 186 has no id. Shouldn't it be "custom_pct_radiobutton"?

**Comment by lukefromdc** [comment]
Just confirmed it here, note that aspect ratio at least is retained

**Comment by UbuntuMetal** [comment]
Confirmed here, too - a 1400x1400px image gets resized to 1000x1000px when choosing 50%, and 3000x2246px ends up 1000x749px. This is in Ubuntu 22.04 with Caja 1.26.0.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja-extensions/pull/117
will fix this, needs another review if possible

**Comment by raveit65** [comment]
https://github.com/mate-desktop/caja-extensions/commit/9801ebca7a7072b68da3c816a20558080316bb06 is merged.

**Comment by Cyrille37** [comment]
Hi

I use MATE 1.26.0 (_Linux Mint 21.3 Virginia 64-bit_) with Caja 1.2.6.0 and this bug is not resolved.
Which version should be used ?

Thanks & regards
