### ISSUE TITLE
support gupnp-1.6?

### ISSUE THREAD

**Issue by jhgit** [mate-desktop/caja-extensions#110]
#### Expected behaviour

Don't fail to find upnp if gupnp-1.6 is installed.

#### Actual behaviour

configure fails to find upnp if gupnp-1.6 is installed (instead of gupnp-1.2)

#### Steps to reproduce the behaviour

remove any installation of gupnp-1.2
install gupnp-1.6
configure

 observe that UPNP is not found:

    checking for UPNP... no
    checking for UPNP... no
    configure: WARNING: you need gupnp installed to build the upnp plugin (disabling sendto plugin)

#### MATE general version

1.26

#### Package version

n/a

#### Linux Distribution

not distro specific

#### Link to bugreport of your Distribution (requirement)

not specific to a distro, but see related bug after freebsd update to gupnp 1.5.0:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=263599

**Comment by jhgit** [comment]
'configure' works and the build succeeds with the following patch:

```
--- configure.ac.orig   2021-08-06 13:34:59.000000000 -0600
+++ configure.ac        2022-05-02 09:26:48.190928000 -0600
@@ -214,6 +214,8 @@ if test "x$enable_sendto" = "xyes"; then
             fi
             ;;
             upnp)
+                PKG_CHECK_MODULES(UPNP, gupnp-1.6 >= $GUPNP_REQUIRED,
+                    enable_upnp=yes AC_DEFINE([HAS_GUPNP_VERSION_1_2], 1, ["Version is at least 1.2"]), enable_upnp=no)
                 PKG_CHECK_MODULES(UPNP, gupnp-1.2 >= $GUPNP_REQUIRED,
                     enable_upnp=yes AC_DEFINE([HAS_GUPNP_VERSION_1_2], 1, ["Version is at least 1.2"]), enable_upnp=no)
                 PKG_CHECK_MODULES(UPNP, gupnp-1.0 >= $GUPNP_REQUIRED,
```

todo: run testing

**Comment by heftig** [comment]
Definitely not going to work: 

```
upnp.c:151:9: warning: implicit declaration of function 'gupnp_service_info_get_introspection_async';
              did you mean 'gupnp_service_info_introspect_async'? [-Wimplicit-function-declaration]
```

**Comment by raveit65** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=2145142
and fedora-devel list https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/VWBNK3UCUOIYNILUD2HKID3NG4CAVGTD/#VWBNK3UCUOIYNILUD2HKID3NG4CAVGTD

There is more to do. For the moment i disabled gupnp support for fedora rawhide with this patch.
```
From d390cb9d6db7ffd97573ec7f0f90f2ac56d3c9a7 Mon Sep 17 00:00:00 2001
From: raveit65 <mate@raveit.de>
Date: Wed, 23 Nov 2022 21:38:26 +0100
Subject: [PATCH] build without gupnp

---
 configure.ac | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/configure.ac b/configure.ac
index c8fb513..bdb4575 100644
--- a/configure.ac
+++ b/configure.ac
@@ -119,7 +119,7 @@ if test "x$enable_sendto" = "xyes"; then
         GTHREAD_REQUIRED=2.6.0
         DBUS_REQUIRED=1.0
         DBUS_GLIB_REQUIRED=0.60
-        GUPNP_REQUIRED=0.13
+#        GUPNP_REQUIRED=0.13
         PKG_CHECK_MODULES(SENDTO,
                 glib-2.0    >= $GLIB_REQUIRED
                 gthread-2.0 >= $GTHREAD_REQUIRED
@@ -130,7 +130,7 @@ if test "x$enable_sendto" = "xyes"; then
         AC_SUBST(SENDTO_LIBS)
 
     # The full list of plugins
-    allowed_sendto_plugins="emailclient gajim caja-burn pidgin removable-devices upnp"
+    allowed_sendto_plugins="emailclient gajim caja-burn pidgin removable-devices"
 
     sendto_plugin_error_or_ignore()
     {
-- 
2.38.1
```
And use configure option `--with-sendto-plugins=emailclient,gajim,caja-burn,pidgin,removable-devices` to be sure.

**Comment by raveit65** [comment]
@mate-desktop/core-team 
Fedora 38 is released  and the plugin can't be build any more.
I guess ubuntu will be the next distro where it failed.

**Comment by raveit65** [comment]
Can you please help testing https://github.com/mate-desktop/caja-extensions/pull/120 with your upnp media-server?

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/caja-extensions/commit/1d21084e8ffdacb3e3b60840261b6d456d23887e

**Comment by raveit65** [comment]
stable 1.26 https://github.com/mate-desktop/caja-extensions/commit/652e145d2c5e2a9658eed7a665fe5a295503940b
