### ISSUE TITLE
caja-share is not working on Ubuntu MATE 22.04 LTS, shows 'net usershare' returned error 255 in Folder Sharing window

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/caja-extensions#111]
#### Expected behaviour
Caja Shared folders are configured and work normally.

#### Actual behaviour
User is unable to configure and use shared folders from Caja.

> ![fs-2204-error-255](https://user-images.githubusercontent.com/309456/167288911-63917467-5d9b-4ddf-a8d8-1bc2af2a17a4.png)
> 'net usershare' returned error 255

Have error message in `~/.xsession-errors` file also

> Caja-Share-Message: 11:11:41.190: Called "net usershare add" but it failed: 'net usershare' returned error 255

#### Steps to reproduce the behaviour
1. Install relevant packages by `sudo apt-get install caja-share samba`
2. Reboot
3. Open Caja, select folder, do right mouse click on it, choose Sharing Options, tick all checkboxes, click Create Share

#### MATE general version
1.26.0

#### Package version
1.26.0-1

#### Linux Distribution
Ubuntu MATE 22.04 LTS

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1972057

**Comment by huangsx0213** [comment]
I have the same issue on Ubuntu MATE 22.04 LTS.

**Comment by N0rbert** [comment]
From https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1972057/comments/4 I can cite the following:

>A quick grep shows that bin:caja-share from src:caja-extensions needs the same patch[1] as nautilus-share. Note I didn't see the "-l" parameter being used in any of the above comments, though, so it might be something else. But "-l" is definitely no longer accepted in samba 4.15.x.
>
>1. https://git.launchpad.net/ubuntu/+source/nautilus-share/commit/?id=3ef14c2846ae7d1242cf1ea4358165abea0a03c0

So above should be applied to Caja extensions.

**Comment by colibris79** [comment]
@rbuj how can we get this fixed for Mint 21/Ubuntu 22.04?

**Comment by lukefromdc** [comment]
To get it there, a new release of the 1.26 branch will need to contain this fix

**Comment by raveit65** [comment]
@lukefromdc Let me know when i should make a new release.

**Comment by lukefromdc** [comment]
For this package, I am only seeing one other open PR
https://github.com/mate-desktop/caja-extensions/pull/113
related to a guix system and concerning translations which I am not in position to test as I only know one language and know little of how gettext or transifex work. It has one "unofficial approving review"  from https://github.com/cwendling which you need to read the comments to see. 

Someone else could test that and merge it if it works, after that would be really good timing. If that's not going to happen soon, a release now to get the fix out for folder sharing would also be an option

**Comment by lukefromdc** [comment]
That is now done, this should be ready for release, also there are no more open PR's in mate-desktop right now

**Comment by colibris79** [comment]
@lukefromdc @raveit65  that would be great! It is such a useful extension (that I have been using for years...)

**Comment by lukefromdc** [comment]
Release is out

**Comment by aryodegrave** [comment]
how to fix this problem?

**Comment by colibris79** [comment]
@lukefromdc @raveit65 not available in repos yet?

**Comment by lukefromdc** [comment]
I have no control over what any distro does. Only those who are part of a distro's
team as well as the MATE team (or just part of the distro's team) control that

**Comment by raveit65** [comment]
I pushed it to fedora some weeks ago https://src.fedoraproject.org/rpms/caja-extensions.
I am not responsible for ubuntu-mate. Feel free switch to great fedora which is always actual.
Or file out bugs against ubuntu.

**Comment by colibris79** [comment]
@lukefromdc @raveit65 thanks for your answers. A fix has been published a few days ago (sorry, forgot to check):
[https://launchpad.net/~lvoytek/+archive/ubuntu/caja-extensions-fix-samba-share]
I was getting also the rmb package and converting it to deb.

**Comment by masakkre** [comment]
> @lukefromdc @raveit65 thanks for your answers. A fix has been published a few days ago (sorry, forgot to check): https://launchpad.net/~lvoytek/+archive/ubuntu/caja-extensions-fix-samba-share I was getting also the rmb package and converting it to deb.

Not working for me. I apply the fix using the repo and now i can do the sare without error, but when I browse for the folder from other computer, I can't see it. I try to reach the folder using caja smb://computer/folder but without luck too.

I am using Ubuntu-mate 22.04

**Comment by lukefromdc** [comment]
It is possible the package you converted to .deb format installed something in the wrong 
place or expected something to be installed elsewhere than where Debian installs it.
Since you don't get a crash you don't have a failure to find a library at least.

**Comment by masakkre** [comment]
> It is possible the package you converted to .deb format installed something in the wrong place or expected something to be installed elsewhere than where Debian installs it. Since you don't get a crash you don't have a failure to find a library at least.

I don´t get any error on the repo install or upgrading my packages. Now I am thinking on it, I had the caja-share and dependencys allready installed, I got the repo install and upgrade the packages. Perhaps I must unistall them and do a fresh install of caja-share from the new repo?  It is really weird, couse if i use  net usershare list in a terminal, the shared folders are listed, but not accesible from other computers.

Thank you for your help!!

**Comment by lukefromdc** [comment]
Try uninstalling/purging and reinstalling,beyond that I don't have any futher suggestions

**Comment by fixups** [comment]
I am using Ubuntu MATE 20.04 and I still have this exact same issue. Apparently the fix has not been released for 20.04, which is an LTS version, and should still be supported.

Is there anything you can do, or can you suggest who I should contact?

Thank you in advance.

**Comment by N0rbert** [comment]
It is great that both Debian 11 and 12 (testing) is not affected by the bug.
Here I ran only one extra command:

```
sudo usermod -a -G sambashare $USER
```

to get user-shares working.

**Comment by fixups** [comment]
I'm sorry to insist, but can we hope for a fix for Ubuntu MATE 20.04?

**Comment by lukefromdc** [comment]
I and the other team members (excluding anyone who is also part of Ubuntu-MATE) have absolutely no control over what Ubuntu does, the Ubuntu-MATE devs would be the ones to ask.
