### ISSUE TITLE
"Open in Terminal" does not open the selected directory

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/caja-extensions#118]
#### Expected behaviour
* The selected directory in caja should be opened in File -> "Open in Terminal" (in this case ~/.config/, not ~/.config/)

#### Actual behaviour
* ~/.config/caja/ will be opened in the terminal, not ~/.config/
![3](https://github.com/mate-desktop/caja/assets/6416073/240b5e41-8daf-4a30-8fa7-f07791965c34)

#### Steps to reproduce the behaviour
* In caja, open a sub-directory in caja, for example ~/.config/caja
* Go back one directory level, in this case to ~/.config/
* Open File -> "Open in Terminal"

![1](https://github.com/mate-desktop/caja/assets/6416073/84fe3a49-8cee-4b50-b3fe-713678b4f65f)
![2](https://github.com/mate-desktop/caja/assets/6416073/f6826940-29cd-45b8-aa31-5fd159f9f2ce)

#### MATE general version
1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu MATE 22.04, Ubuntu MATE 23.04, Trisquel 11.

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/+source/caja/+bug/2030290

**Comment by davidhedlund** [comment]
* https://github.com/mate-desktop/caja/issues/1736

**Comment by bttrx** [comment]
I think, this is the expected behavior. In your screenshots 2 and 3 the 'caja' folder is selected/highlighted.

**Comment by davidhedlund** [comment]
> I think, this is the expected behavior. In your screenshots 2 and 3 the 'caja' folder is selected/highlighted.

You are right. Thank you.

**Comment by davidhedlund** [comment]
Solved.

**Comment by davidhedlund** [comment]
Solved.
