### ISSUE TITLE
Add secure deletion extension

### ISSUE THREAD

**Issue by somename11111** [mate-desktop/caja-extensions#13]
I miss the [nautilus-wipe](https://packages.debian.org/jessie/nautilus-wipe) extension in caja.

**Comment by fingus** [comment]
Good idea! would like it too

**Comment by wiwwo** [comment]
Hey there!
Any news on this Feature Request?

Thanks!
Wiwwo

**Comment by Overlord23** [comment]
That would be nice! Actually we can only run wipe from terminal.

**Comment by monsta** [comment]
Done in a 3rd party repo: https://github.com/Fred-Barclay/Caja-Wipe
