### ISSUE TITLE
missing rabbitvcs extension (as well as compare)

### ISSUE THREAD

**Issue by bperrybap** [mate-desktop/caja-extensions#14]
Mint 17.1 32 bit mate edition.

Caja seems to be missing some of the useful extensions that are available in the repo for Nautilus and Nemo.

IMO, caja should have the same client extensions as nemo to provide a consistent/similar "mint" experience on both mate and cinnamon.

While there are more, the two that I find most useful that are missing are:
- rabbitvcs
- compare

There is a caja rabbitvcs client available in the rabbitvcs repo, so rolling a  package shouldn't be that difficult.
https://github.com/rabbitvcs/rabbitvcs/tree/master/clients/caja

In the larger picture, it would be great if caja had all the same extensions as nemo.
When it doesn't, it makes caja seem like it is not getting the same level of support as nemo.

**Comment by bperrybap** [comment]
I don't understand why this was closed with reference to a rabbitvcs repo issue.
I guess I'm not understanding who is the maintainer of which repo of rabbitvcs vs the caja extensions and where to report Linux Mint caja extension issues.

What about the other missing caja extensions? there are several besides just rabbitvcs and compare.
Should I open a separate issue in this repo for each missing caja extension that exists in nemo?

**Comment by monsta** [comment]
This is not closed (yet). What's shown above is a reference to a closed issue.

What is the problem with rabbitvcs? Do you wish to have a .deb with that Caja extension to use in Debian/Ubuntu/Mint? If so, this is not for us (MATE developers) to handle.

**Comment by monsta** [comment]
Well, if there won't be any more feedback, I'm closing it as the extension does exist in third-party repo, and the installation is trivial as described in README there.

**Comment by bperrybap** [comment]
I seem to keep going in circles trying to get rabbitvcs into the stock/default Mint Mate repo.
Do you have any pointers as to where to file the issue?

**Comment by monsta** [comment]
Why not try Launchpad first?
https://launchpad.net/ubuntu/+source/rabbitvcs/+bugs

Also I noticed it's been asked on Debian bug tracker:
https://bugs.debian.org/782113

**Comment by raveit65** [comment]
I don't know why and when and if it works, put someone added 'Caja extension for RabbitVCS' to fedora a while ago :-)
http://pkgs.fedoraproject.org/cgit/rpms/rabbitvcs.git/tree/rabbitvcs.spec#n107
