### ISSUE TITLE
port nautilus-seafile to caja

### ISSUE THREAD

**Issue by bertvandepoel** [mate-desktop/caja-extensions#18]
I would be really nice if, just like nautilus-dropbox, nautilus-seafile was ported to caja. I tried to convince them on https://github.com/haiwen/seafile-client/pull/575 but they considered it not their task.

Seafile is a fully open source alternative to dropbox that can be easily self-hosted.

**Comment by infirit** [comment]
Sorry but unless someone steps up to maintain it this is not likely to happen. There is no manpower to take on new packages like this. Closing for now until someone is willing to do the work and then maintain it.

**Comment by quesada** [comment]
Adding a +1 in case it matters
