### ISSUE TITLE
gksu loaded even if disabled

### ISSUE THREAD

**Issue by claurita** [mate-desktop/caja-extensions#19]
caja 1.10.4 caja-gksu 1.10.1 on debian sid 32bits
When gksu is disabled in the preferences, the extension is loaded anyway and works correctly.
When enabled, is loaded twice and the second instance correctly fires errors in .xsession-errors about
"Refusing to add non-unique action 'Gksu::open_as_root' to action group 'DirExtensionsMenuGroup"
and several other related gtk errors on every action done in ui.
I straced the process and noticed that all installed extension libraries are always loaded, despite the preference status. I suppose this is by design. But other extensions are not activated if disabled, while gksu is.
I searched anywhere to find a trace of previous installations (mate upgrade is not always straightforward on debian ;-)) but i found nothing. Tell me if I can give other details or run any kind of test.
Regards
Claudio

**Comment by flexiondotorg** [comment]
This was due to a bug introduced in MATE 1.10. I've just tested MATE 1.16 and MATE 1.17 and this issue is resolved. I actually think it was fixed in the MATE 1.12 release.
