### ISSUE TITLE
Feature Request: gksu extension configure option to use gksudo instead of gksu

### ISSUE THREAD

**Issue by NP-Hardass** [mate-desktop/caja-extensions#20]
In caja's preferences window, extensions tab, a selected extension may be customized if options are available.   I'd like to request that the gksu extension have an option added that allows toggling of the actual command used, between gksu and gksudo.

**Comment by monsta** [comment]
Doesn't setting the mode in ```gksu-properties``` tool work for the extension?

**Comment by NP-Hardass** [comment]
So it does.  Required logging out and back in again, but did the trick.  Thanks.
