### ISSUE TITLE
feature request: Be able to tag files

### ISSUE THREAD

**Issue by fbarriga** [mate-desktop/caja-extensions#27]
I'm currently working on an extension to add support to manage Tags on files. This extension is a new tab on the File Properties window.
You can see the tags associated with a file, add new tags and remove existing ones.

Demo:
![demo_tag_property_page](https://cloud.githubusercontent.com/assets/718207/24325415/47e106a0-1177-11e7-9ba2-ff7d0b6eac08.gif)

Features:
- Each time you add a new tag, it will be added to a list of recently used tags. The next time you add an existing tag, the autosuggestion/autocomplete will appear on the text input.

Current Limitations:
- Cannot edit tags of multiple files at the same time.

Missing features due to lacking support for extension settings/preferences:
- Clear the list of tags on the autocomplete feature
- Remove specific tags from the autocomplete feature
- Configure the max amount of entries to have in the recent tags

Those missing features can be worked-around with `dconf-editor`

TODO:
- Check corner cases (read only/permissions/missing support for xattrs/multi-thread/file rename/file remove/etc)
- Look for memory leaks

The current name for this extension is `caja-xattr-tags-property-page-extension` which I think is too long.. any suggestion ?

**Comment by raveit65** [comment]
Nice.....

**Comment by fbarriga** [comment]
PR with the implementation: https://github.com/mate-desktop/caja-extensions/pull/33

**Comment by raveit65** [comment]
> The current name for this extension is caja-xattr-tags-property-page-extension which I think is too long.. any suggestion ?

xattr-tags-property-page should be enough as it is part of caja-extensions package ;-)
Maybe it makes sense to add the new plugin into the existent xattr-tags extension?
I think most people want to read and write tags.

**Comment by fbarriga** [comment]
@raveit65 thanks for the suggested name!
It doesn't make too much sense to mix them because:
- the code is completely independent, keep it simple and modular
- one add a new page on the properties and the other add a new column so no benefit of mixing them

**Comment by fbarriga** [comment]
Already implemented: https://github.com/mate-desktop/caja-xattrs
