### ISSUE TITLE
W: caja-xattr-tags: spelling-error-in-description extention extension

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/caja-extensions#36]
W: caja-xattr-tags: spelling-error-in-description extention extension
N: 
N:    Lintian found a spelling error in the package description. Lintian has a
N:    list of common misspellings that it looks for. It does not have a
N:    dictionary like a spelling checker does. It is particularly picky about
N:    spelling and capitalization in package descriptions since they're very
N:    visible to end users.
N:    
N:    Severity: minor, Certainty: certain
N:    
N:    Check: description, Type: binary, udeb

**Comment by monsta** [comment]
Well, this time it's a debian packaging issue :slightly_smiling_face: 
Fixed it for our packaging in https://github.com/mate-desktop/debian-packages/commit/8b0060eb72943e5273e921dcd18558527d5da448

**Comment by sunweaver** [comment]
@monsta: ouch, you are right...
Thanks!

On Tuesday, July 25, 2017, monsta wrote:
> Well, this time it's a debian packaging issue 🙂
> Fixed it for our packaging in mate-desktop/debian-packages@8b0060e 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼
>

-- 
Sent from my Fairphone (running Sailfish OS)...
