### ISSUE TITLE
caja-extension-sendto-upnp doesn't build with gupnp-1.2

### ISSUE THREAD

**Issue by jonsger** [mate-desktop/caja-extensions#52]
On openSUSE Tumbleweed we only ship gupnp-1.2 (1.2.1), so no gupnp-1.0. So we can't build caja-extension-sendto-upnp out-of-the-box anymore.

I created the following patch to let it build again:
```
--- configure.ac
+++ configure.ac
@@ -196,7 +196,7 @@
             fi
             ;;
             upnp)
-                PKG_CHECK_MODULES(UPNP, gupnp-1.0 >= $GUPNP_REQUIRED,
+                PKG_CHECK_MODULES(UPNP, gupnp-1.2 >= $GUPNP_REQUIRED,
                     enable_upnp=yes, enable_upnp=no)
                 if test "${enable_upnp}" != "yes" ; then
                     sendto_plugin_error_or_ignore "you need gupnp installed to build the upnp plugin"
--- sendto/plugins/upnp/upnp.c
+++ sendto/plugins/upnp/upnp.c
@@ -206,7 +206,7 @@
                return FALSE;
        g_free (upload_cmd);
 
-       context_manager = gupnp_context_manager_new (NULL, 0);
+       context_manager = gupnp_context_manager_create (0);
        g_assert (context_manager != NULL);
        g_signal_connect (context_manager, "context-available",
                          G_CALLBACK (on_context_available), NULL);
```

Is this the right way to do it? Would you accept a proper PR, the configure.ac thing needs some more love.

**Comment by vkareh** [comment]
@jonsger - gupnp 1.2 was tagged a few months ago, most distros won't have that available that quickly. The "proper" way (if there's such a thing) would be to have a conditional check in `configure.ac` that checks which version and set a variable like `HAS_GUPNP_VERSION_1_2` or something, then in the code do something like this:
```c
#ifdef HAS_GUPNP_VERSION_1_2
context_manager = gupnp_context_manager_create (0);
#else
context_manager = gupnp_context_manager_new (NULL, 0);
#endif
```
Please send a pull request and we can start testing. Alternatively, you can just distro-patch Tumbleweed, but then you'll need to maintain that extra configuration on your side...
