### ISSUE TITLE
Open-in-Terminal in context menu of items in location bar?

### ISSUE THREAD

**Issue by TwlyY29** [mate-desktop/caja-extensions#60]
Hi,

let me reaffirm #31 by saying that the open-terminal is really great. 
Is there a way to integrate the open-terminal-call into the context menu of a 'folder-button' in caja's location bar? 
Sometimes, I'd like to open a terminal in a place a little up in the hierarchy. Also, in list view that takes up the whole height of the window, I sometimes can't find a spot to right click the current folder. Of course, the shortcut is an option I am currently getting comfortable with. But it doesn't help me with my first 'issue'. 
If you point me to the place where the context menus are created, I'll be happy to contribute this feature.

Best
Mirco

**Comment by ShafinKhadem** [comment]
I think I have a solution to your problem extending #31 : change the script ```~/.config/caja/scripts/open-terminal-here``` as following (the following script opens a gnome-terminal in all selected directories, if nothing is selected it opens in current directory):
```bash
#!/bin/bash
#
# This script opens a gnome-terminal in all selected directories, if nothing is selected it opens in current directory.
#
# You need to have caja-actions installed to use scripts.
# Put this file in your ~/.config/caja/scripts/ directory. Then:
# chmod +x ~/.config/caja/scripts/open-terminal-here
# vim ~/.config/caja/accels
# add the following line
# (gtk_accel_path "<Actions>/ScriptsGroup/script_file:\\s\\s\\shome\\sUSER\\s.config\\scaja\\sscripts\\sopen-terminal-here" "F4")
# where USER is your user name. This binds the script to F4, but of course you can change the shortcut as you like.
# Quit Caja (caja -q) and restart it.
# I've tested it on Ubuntu 19.10.
#
# Extended from following sources:
# https://github.com/mate-desktop/caja-extensions/issues/31#issuecomment-385655453
# http://misawascriptkid.blogspot.com/2012/06/caja.html
# https://forums.linuxmint.com/viewtopic.php?p=773382&sid=9939ce160bd97313f849367231eb721a#p773382
# http://g-scripts.sourceforge.net/nautilus-scripts/Execute/Open%20terminal/terminal-here


if [[ -z "$CAJA_SCRIPT_SELECTED_FILE_PATHS" ]]; then
    uri="${CAJA_SCRIPT_CURRENT_URI:7}"
    exec gnome-terminal --working-directory="${uri//%20/ }"
    exit
fi

while read path; do
    if [[ -d "$path" ]]; then
        gnome-terminal --working-directory="$path" &disown
    fi
done <<< "$CAJA_SCRIPT_SELECTED_FILE_PATHS"

```

**Comment by TwlyY29** [comment]
Hey, that's great and solves the issue flawlessly. Thanks!
