### ISSUE TITLE
caja-sendto does not send Email with file (from terminal or by "Send To" GUI option)

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/caja-extensions#80]
#### Expected behaviour
* caja-sendto sends e-mail with the file attachment to the specified e-mail address

#### Actual behaviour
* caja-sendto does not send e-mail, opens Evolution main window instead

#### Steps to reproduce the behaviour
1. Install Ubuntu MATE 20.04 LTS
2. Configure Email account in the default E-mail client - GNOME Evolution
3a. Open Atril, open some file in it (for example /usr/share/cups/data/default-testpage.pdf ), select File->Send To
3b. Open terminal and execute command `caja-sendto /usr/share/cups/data/default-testpage.pdf`
4. In the *Send To...* window set *Send as* to *Email* and provide correct E-mail address in *Send to*, click *Send*

#### MATE general version
1.24.0

#### Package version
1.24.0-1

#### Linux Distribution
Ubuntu 20.04 LTS

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/caja-extensions/+bug/1864432

**Comment by N0rbert** [comment]
What is interesting - it works normally if I install Thunderbird and specify it as default e-mail application.

**Comment by tamplan** [comment]
Hi,

Which version of evolution are you using? Greater than 3.0?

Confirmed with Evolution version 3.36.1-2 on Ubuntu 20.04 too.

**Comment by raveit65** [comment]
Guys , can someone please test https://github.com/mate-desktop/caja-extensions/pull/84?
I don't use evolution for myself.....
